# This is free software, licensed under the Apache License, Version 2.0

#
# Copyright (C) 2024 Hilman Maulana <hilman0.0maulana@gmail.com>

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI for speedtestcpp

LUCI_DEPENDS:=+speedtestcpp
LUCI_DESCRIPTION:=LuCI support for speedtestcpp

PKG_MAINTAINER:=Hilman Maulana <hilman0.0maulana@gmail.com>
PKG_VERSION:=2.1
PKG_LICENSE:=Apache-2.0

PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL=https://github.com/animegasan/luci-app-speedtest.git
PKG_SOURCE_DATE:=2024-04-14
PKG_SOURCE_VERSION:=238cfff4e9f809dcd2380fae39d4014a0453afa1
PKG_MIRROR_HASH:=cd194f2849b215fda62229535ab9f88171a4e33035fd9730b8fa6c696e09c797


include $(TOPDIR)/feeds/luci/luci.mk


# call BuildPackage - OpenWrt buildroot signature

